export const fontFamilies = [
    // 시스템 폰트
    {name: 'Arial', source: 'system'},
    {name: 'Times New Roman', source: 'system'},
    {name: 'Georgia', source: 'system'},
    {name: 'Verdana', source: 'system'},
    {name: 'Trebuchet MS', source: 'system'},
    {name: 'Courier New', source: 'system'},
    {name: 'Malgun Gothic', source: 'system'},
    {name: 'Gulim', source: 'system'},
    {name: 'Dotum', source: 'system'},
    {name: 'Batang', source: 'system'},
    {name: 'Calibri', source: 'system'},
    // 번들 폰트 (@fontsource)
    {name: 'Noto Sans', source: 'bundled'},
    {name: 'Noto Sans KR', source: 'bundled'},
    // Google Fonts — Sans-serif
    {name: 'Inter', source: 'google'},
    {name: 'Roboto', source: 'google'},
    {name: 'Open Sans', source: 'google'},
    {name: 'Lato', source: 'google'},
    {name: 'Montserrat', source: 'google'},
    {name: 'Poppins', source: 'google'},
    {name: 'Raleway', source: 'google'},
    {name: 'Nunito', source: 'google'},
    {name: 'Quicksand', source: 'google'},
    {name: 'Josefin Sans', source: 'google'},
    {name: 'Comfortaa', source: 'google'},
    {name: 'DM Sans', source: 'google'},
    {name: 'Outfit', source: 'google'},
    {name: 'Plus Jakarta Sans', source: 'google'},
    {name: 'Figtree', source: 'google'},
    // Google Fonts — Serif
    {name: 'Playfair Display', source: 'google'},
    {name: 'Merriweather', source: 'google'},
    {name: 'Lora', source: 'google'},
    {name: 'Crimson Text', source: 'google'},
    {name: 'EB Garamond', source: 'google'},
    {name: 'Cormorant Garamond', source: 'google'},
    {name: 'Libre Baskerville', source: 'google'},
    {name: 'Cinzel', source: 'google'},
    // Google Fonts — Display / Decorative
    {name: 'Oswald', source: 'google'},
    {name: 'Bebas Neue', source: 'google'},
    {name: 'Lobster', source: 'google'},
    {name: 'Pacifico', source: 'google'},
    {name: 'Righteous', source: 'google'},
    {name: 'Fredoka One', source: 'google'},
    {name: 'Abril Fatface', source: 'google'},
    {name: 'Titan One', source: 'google'},
    // Google Fonts — Handwriting
    {name: 'Dancing Script', source: 'google'},
    {name: 'Caveat', source: 'google'},
    {name: 'Sacramento', source: 'google'},
    {name: 'Indie Flower', source: 'google'},
    {name: 'Shadows Into Light', source: 'google'},
    {name: 'Satisfy', source: 'google'},
    // Google Fonts — Monospace
    {name: 'Source Code Pro', source: 'google'},
    {name: 'Fira Code', source: 'google'},
    {name: 'Space Mono', source: 'google'},
    // Google Fonts — 한국어
    {name: 'Gothic A1', source: 'google'},
    {name: 'IBM Plex Sans KR', source: 'google'},
    {name: 'Noto Serif KR', source: 'google'},
    {name: 'Nanum Gothic', source: 'google'},
    {name: 'Nanum Myeongjo', source: 'google'},
    {name: 'Nanum Brush Script', source: 'google'},
    {name: 'Nanum Pen Script', source: 'google'},
    {name: 'Black Han Sans', source: 'google'},
    {name: 'Do Hyeon', source: 'google'},
    {name: 'Jua', source: 'google'},
    {name: 'Gaegu', source: 'google'},
    {name: 'Single Day', source: 'google'},
    {name: 'Sunflower', source: 'google'},
    {name: 'Gowun Dodum', source: 'google'},
    {name: 'Gowun Batang', source: 'google'},
    {name: 'Hahmlet', source: 'google'},
    {name: 'Hi Melody', source: 'google'},
    {name: 'Song Myung', source: 'google'},
    {name: 'Yeon Sung', source: 'google'},
    {name: 'East Sea Dokdo', source: 'google'},
    {name: 'Gamja Flower', source: 'google'},
    {name: 'Cute Font', source: 'google'},
];
